export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_PLAN = 'GET_PLAN';
export const SAVE_PLAN = 'SAVE_PLAN';
export const DELETE_PLAN = 'DELETE_PLAN';
export const LOADING_PLAN = 'LOADING_PLAN';
export const STOP_LOADING_PLAN = 'STOP_LOADING_PLAN';

export const GET_ROUTINE = 'GET_ROUTINE';
export const UPDATE_ROUTINE = 'UPDATE_ROUTINE';
export const CREATE_ROUTINE = 'CREATE_ROUTINE';
export const LOADING_ROUTINE = 'LOADING_ROUTINE';
export const STOP_LOADING_ROUTINE = 'STOP_LOADING_ROUTINE';
export const GET_ROUTINE_ERRORS = 'GET_ROUTINE_ERRORS';
export const CLEAR_ROUTINE_ERRORS = 'CLEAR_ROUTINE_ERRORS';

export const GET_ROUTINE_DAY = 'GET_ROUTINE_DAY';
export const SAVE_ROUTINE_DAY = 'SAVE_ROUTINE_DAY';
export const SAVE_ADD_AB = 'SAVE_ADD_AB';
export const SAVE_ADD_DAY = 'SAVE_ADD_DAY';
export const LOADING_ROUTINE_DAY = 'LOADING_ROUTINE_DAY';
export const STOP_LOADING_ROUTINE_DAY = 'STOP_LOADING_ROUTINE_DAY';

export const UPDATE_WORKOUT = 'UPDATE_WORKOUT';
export const GET_WORKOUT = 'GET_WORKOUT';
export const GET_CREATE_WORKOUT = 'GET_CREATE_WORKOUT';
export const SELECT_WORKOUT = 'SELECT_WORKOUT';
export const CLEAR_SELECTED_WORKOUT = 'CLEAR_SELECTED_WORKOUT';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';
export const LOADING_WORKOUT = 'LOADING_WORKOUT';
export const STOP_LOADING_WORKOUT = 'STOP_LOADING_WORKOUT';

export const START_REST_TIMER = 'START_REST_TIMER';
export const STOP_REST_TIMER = 'STOP_REST_TIMER';

export const GET_EXERCISE = 'GET_EXERCISE';
export const GET_ALL_EXERCISE = 'GET_ALL_EXERCISE';
export const SAVE_EXERCISE = 'SAVE_EXERCISE';
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const LOADING_EXERCISE = 'LOADING_EXERCISE';
export const STOP_LOADING_EXERCISE = 'STOP_LOADING_EXERCISE';

export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const SAVE_CATEGORY = 'SAVE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const LOADING_CATEGORY = 'LOADING_CATEGORY';
export const STOP_LOADING_CATEGORY = 'STOP_LOADING_CATEGORY';

export const GET_SETTINGS = 'GET_SETTINGS';
export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const LOADING_SETTINGS = 'LOADING_SETTINGS';
export const STOP_LOADING_SETTINGS = 'STOP_LOADING_SETTINGS';